### PR TITLE
Explain how to start https devserver in the readme README.md

### PR DESCRIPTION
**Pull request by toger5**

### CODE REVIEW

**Review by robintown — COMMENTED** [review]
Hmm, does this actually work? Last time I tried it, I wasn't able to use Element Call from a mobile device this way, because an HTTP dev server on a host other than localhost doesn't count as a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).

**Review by robintown — APPROVED** [review]
Oh, now I've seen https://github.com/vector-im/element-call/pull/1243

**Comment by toger5** [comment]
Yes this is mostly documentiong https://github.com/vector-im/element-call/pull/1243
So that we dont forget how to do that the next time I want to.

**Comment by dbkr** [comment]
`prettier -w README.md` should make this happy: it probably just wants it wrapped to some number of columns.

**Pull request closed without merging**
