### PR TITLE
Show controls on tap/hover on small screens

### PR DESCRIPTION
**Pull request by robintown**
This changes the mobile landscape view to automatically hide the controls, giving more visibility to the video underneath, and show them on tap/hover.

### CODE REVIEW

**Comment by robintown** [comment]
Sadly this change causes the controls overlay to glitch in and out of existence on Firefox. We should discuss what to do about this tomorrow.

**Comment by robintown** [comment]
Added the check for Firefox as discussed, it doesn't totally fix the layering issue but it manifests very rarely now.

**Comment by fkwp** [comment]
no glitches on iOS (Safari)

**Review by AndrewFerr — APPROVED** [review]
My React knowledge is still patchy, but this LGTM from what I can tell :slightly_smiling_face:

**Pull request merged**
