### PR TITLE
Add redirects to netlify deployment

### PR DESCRIPTION
**Pull request by dbkr**

### CODE REVIEW

**Comment by ara4n** [comment]
only comment is that it feels a bit weird that a redirect config file is sitting in /scripts (which would typically be executable scripts, no?)

**Comment by dbkr** [comment]
yeah - wasn't sure where else to put it: a '/support' directory or somewhere?

**Comment by ara4n** [comment]
perhaps `config` (and move default.conf into there too?)

**Comment by ara4n** [comment]
lgtm otherwise.

**Comment by dbkr** [comment]
oh yeah, that's probably nicer

**Pull request merged**
