### PR TITLE
Remove unecassary state for lobby device initialization

### PR DESCRIPTION
**Pull request by toger5**
@daniel-abramov

### CODE REVIEW

**Review by daniel-abramov — APPROVED** [review]
Cool!

Do we need `videoAvailableAndEnabled`? It seems like it's not being used anymore if we rely on `videoEnabled`? (same for the audio counterpart) We only use it in an `onPress` callback, but it the `muted` does not use it anymore.

**Comment by toger5** [comment]
@daniel-abramov and for the actual value we pass the the userChoices.
It makes things more readbale imo.

**Comment by daniel-abramov** [comment]
> @daniel-abramov and for the actual value we pass the the userChoices. It makes things more readbale imo.

But should not we refer to the same value in `muted` and `onPress`?

**Comment by toger5** [comment]
@daniel-abramov you are right. Since the button is disabled we never get into the situation that the video can be enabled/disabeld or changed in any way if the tracks are not available... (no track -> no button interaction)
So this was making it unecassary save (and a bit confusing)

**Review by SimonBrandner — APPROVED** [review]

**Pull request merged**
