### PR TITLE
Remove excessive footer space

### PR DESCRIPTION
**Pull request by dreamflasher**
Improves on https://github.com/element-hq/element-call/issues/1582 until the new layout is implemented.

### CODE REVIEW

**Comment by toger5** [comment]
Thanks! Can you add before/after screenshots?

**Comment by dreamflasher** [comment]
Happy to!

Before at 1366x768 resolution:
before

After at 1366x768 resolution:
after

**Comment by fkwp** [comment]
@americanrefugee ^^

**Comment by americanrefugee** [comment]
@fkwp The screenshot shows only a few pixels between the bottom edge of the bottoms and the bottom of the page, which is not enough.

Can you add a 24 pixel margin between the button row and page bottom?

**Comment by americanrefugee** [comment]
Actually... I forgot about the tool tips on hover. So, we have 2 options:

1. Leave just enough space to show the tooltips below (as currently implemented)
2. Make tooltips show above the buttons, and 24 pixel margin between buttons and page edge

I prefer how it's currently implemented.

**Comment by robintown** [comment]
Discussed this with the team, and we're going to go with Aaron's preference of leaving just enough space to show the tooltips below (about 40px), which strikes a nice compromise between space utilization and visual balance.

**Review by robintown — APPROVED** [review]

**Pull request merged**
