### PR TITLE
Update matrix-js-sdk including MSC4222 support

### PR DESCRIPTION
**Pull request by Half-Shot**
Draft PR to test the latest js-sdk changes.

### CODE REVIEW

**Comment by Half-Shot** [comment]
We tried it just now and found that if you joined into an existing call then you are still missing some state.

**Comment by toger5** [comment]
So we keep the updated js-sdk but keep the memory store?
Or was this blocked by florians 200room account which would make everything super slow?

**Comment by Half-Shot** [comment]
> Or was this blocked by florians 200room account which would make everything super slow?

I would be wary, I'm also a few 10s of rooms in and this would likely spike costs for call.element.io (due to many initial syncs).

**Comment by hughns** [comment]
Memory store was done in https://github.com/element-hq/element-call/pull/2811

**Comment by hughns** [comment]
Superseded by https://github.com/element-hq/element-call/pull/2841

**Pull request closed without merging**
