### PR TITLE
Bump js-sdk dependency to encrypt to-device messages

### PR DESCRIPTION
**Pull request by dbkr**
Fixes https://github.com/vector-im/element-call/issues/257

### CODE REVIEW

**Comment by dbkr** [comment]
Probably want tov wait for https://github.com/matrix-org/matrix-js-sdk/pull/2383 and then bump this to include that

**Comment by robertlong** [comment]
Now I'm confused. Which version of js-sdk is in this PR https://github.com/vector-im/element-call/pull/333

We definitely should wait to roll out E2E if it breaks when the other members don't have E2E keys.

**Comment by dbkr** [comment]
#333 was to pull in the fix for races when muting / unmuting - I've closed it in favour of this one (which is a bit of an arbitrary choice since this one will want to be changed to a new sha once that js-sdk PR is merged).

**Review by robertlong — APPROVED** [review]
Looks good 👍 Let's test more on staging.

**Pull request merged**
