### PR TITLE
gh actions refactor

### PR DESCRIPTION
**Pull request by fkwp**

### CODE REVIEW

**Review by toger5 — APPROVED** [review]

**Review by robintown — DISMISSED** [review]
I think this will break the Netlify PR workflow, since the name of the build artifact hasn't been updated there.

**Comment by fkwp** [comment]
> I think this will break the Netlify PR workflow, since the name of the build artifact hasn't been updated there.

I think I duplicated the workflow for now. And if reusing workflows work as expected I can update the netlify pr as well

**Comment by robintown** [comment]
Oh wait, though there are two build workflows now?

**Comment by fkwp** [comment]
> Oh wait, though there are two build workflows now?

yes. build.yaml    & build_resuable.yaml

**Pull request merged**
